updated models
carys23/Cryptids pull request #26
Opened 2021-03-22 16:11 UTC by carys23

2021-03-22 17:12 UTC, tamjankowska requested changes

2021-03-22 17:12 UTC, tamjankowska commented on cage/cryptids/models.py
> +from django.db import models
Is this line duplicated here?

2021-03-22 17:12 UTC, tamjankowska commented on cage/cryptids/models.py
> +
For your animal model, you may want to think about the kinds of properties you'll want the animal to have, like maybe a name and description, perhaps?

2021-03-23 10:56 UTC, Bukky281 approved these changes

2021-03-23 10:58 UTC, andreigoncearenco approved these changes, later dismissed

2021-03-23 11:03 UTC, Bukky281 submitted a review, later dismissed

2021-03-23 11:05 UTC, carys23 commented
fixed

2021-03-23 11:10 UTC, tamjankowska approved these changes

2021-03-23 11:10 UTC, merged